[phases.setup]
commands = ["npm install"]
node_version = "20"

[phases.build]
commands = [
  "npm run build",
  "npx prisma migrate deploy"
]

[phases.start]
commands = ["npm run start"]

[env]
DATABASE_URL = "${DATABASE_URL}"
NEXTAUTH_URL = "${NEXTAUTH_URL}"
NEXTAUTH_SECRET = "${NEXTAUTH_SECRET}"